# Generated by Django 4.2.22 on 2025-09-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0837_alter_externaldatasource_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="web_analytics_pre_aggregated_tables_version",
            field=models.CharField(choices=[("v1", "v1"), ("v2", "v2")], default="v2", max_length=10, null=True),
        ),
    ]
